# docker-compose.yml
version: '3.8'

services:
  modelbench:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 90s

volumes:
  huggingface-cache: